/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as storeLayoutRouteImport } from './routes/(store)/_layout'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as storeLayoutIndexRouteImport } from './routes/(store)/_layout/index'
import { Route as storeLayoutCartRouteImport } from './routes/(store)/_layout/cart'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as storeLayoutProductIndexRouteImport } from './routes/(store)/_layout/product/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutRoute = storeLayoutRouteImport.update({
  id: '/(store)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutIndexRoute = storeLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storeLayoutRoute,
} as any)
const storeLayoutCartRoute = storeLayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => storeLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const storeLayoutProductIndexRoute = storeLayoutProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => storeLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/vendor': typeof VendorRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cart': typeof storeLayoutCartRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof storeLayoutIndexRoute
  '/product/': typeof storeLayoutProductIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/vendor': typeof VendorRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/cart': typeof storeLayoutCartRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/': typeof storeLayoutIndexRoute
  '/product': typeof storeLayoutProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRoute
  '/vendor': typeof VendorRoute
  '/(store)/_layout': typeof storeLayoutRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/(store)/_layout/cart': typeof storeLayoutCartRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(store)/_layout/': typeof storeLayoutIndexRoute
  '/(store)/_layout/product/': typeof storeLayoutProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/vendor'
    | '/auth/sign-in'
    | '/cart'
    | '/api/auth/$'
    | '/'
    | '/product/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/vendor'
    | '/auth/sign-in'
    | '/cart'
    | '/api/auth/$'
    | '/'
    | '/product'
  id:
    | '__root__'
    | '/admin'
    | '/vendor'
    | '/(store)/_layout'
    | '/auth/sign-in'
    | '/(store)/_layout/cart'
    | '/api/auth/$'
    | '/(store)/_layout/'
    | '/(store)/_layout/product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  VendorRoute: typeof VendorRoute
  storeLayoutRoute: typeof storeLayoutRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout': {
      id: '/(store)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout/': {
      id: '/(store)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof storeLayoutIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/(store)/_layout/cart': {
      id: '/(store)/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof storeLayoutCartRouteImport
      parentRoute: typeof storeLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/_layout/product/': {
      id: '/(store)/_layout/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof storeLayoutProductIndexRouteImport
      parentRoute: typeof storeLayoutRoute
    }
  }
}

interface storeLayoutRouteChildren {
  storeLayoutCartRoute: typeof storeLayoutCartRoute
  storeLayoutIndexRoute: typeof storeLayoutIndexRoute
  storeLayoutProductIndexRoute: typeof storeLayoutProductIndexRoute
}

const storeLayoutRouteChildren: storeLayoutRouteChildren = {
  storeLayoutCartRoute: storeLayoutCartRoute,
  storeLayoutIndexRoute: storeLayoutIndexRoute,
  storeLayoutProductIndexRoute: storeLayoutProductIndexRoute,
}

const storeLayoutRouteWithChildren = storeLayoutRoute._addFileChildren(
  storeLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  VendorRoute: VendorRoute,
  storeLayoutRoute: storeLayoutRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
